sudo: required

dist: bionic

addons:
  apt:
    sources:
      - sourceline: "deb https://packages.chef.io/repos/apt/current bionic main"
    packages:
      - chef-workstation

services: docker

env:
  global:
    - CHEF_LICENSE=accept-no-persist
  matrix:
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-centos-7
    - INSTANCE=default-centos-6
    - INSTANCE=default-amazonlinux
    - INSTANCE=default-debian-9
    - INSTANCE=default-debian-8
    - INSTANCE=amazon-time-amazonlinux

install: echo "skip bundle install"

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chef-workstation/bin/chef shell-init bash)"
  - /opt/chef-workstation/bin/chef gem install test-kitchen kitchen-docker
  - /opt/chef-workstation/bin/chef gem install rubocop rspec
  - /opt/chef-workstation/bin/chef gem install fauxhai -v 5.6.0
script:
  - /opt/chef-workstation/bin/chef --version
  - /opt/chef-workstation/bin/kitchen --version
  - /opt/chef-workstation/bin/cookstyle --version
  - /opt/chef-workstation/bin/cookstyle
  - /opt/chef-workstation/embedded/bin/rspec
  - KITCHEN_YAML=kitchen.docker.yml /opt/chef-workstation/bin/kitchen verify ${INSTANCE}
